CREATE TABLE provinces (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL UNIQUE, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE regions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), province_id uuid NOT NULL REFERENCES provinces(id), slug text NOT NULL, name text NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(province_id,slug));
-- statement-breakpoint
CREATE TABLE cities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), region_id uuid NOT NULL REFERENCES regions(id), slug text NOT NULL, name text NOT NULL, latitude numeric(9,6), longitude numeric(9,6), active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(region_id,slug));
-- statement-breakpoint
CREATE TABLE profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), keycloak_subject text NOT NULL UNIQUE, email text, username text UNIQUE, display_name text NOT NULL, photo_url text, bio text, date_of_birth date, sex_category text CHECK (sex_category IN ('MEN','WOMEN','UNDISCLOSED')), city_id uuid REFERENCES cities(id), privacy jsonb NOT NULL DEFAULT '{"publicProfile":true,"showGym":true}'::jsonb, account_status text NOT NULL DEFAULT 'ACTIVE' CHECK (account_status IN ('ACTIVE','SUSPENDED','BANNED','DELETED')), terms_version text, terms_accepted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
-- statement-breakpoint
CREATE TABLE user_roles (profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, role text NOT NULL CHECK (role IN ('USER','MODERATOR','ADMIN','PERSONAL_TRAINER','JUDGE')), granted_by uuid REFERENCES profiles(id), granted_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(profile_id,role));
-- statement-breakpoint
CREATE TABLE gym_brands (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text NOT NULL UNIQUE, website_url text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE gyms (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), city_id uuid NOT NULL REFERENCES cities(id), brand_id uuid REFERENCES gym_brands(id), slug text NOT NULL, name text NOT NULL, operator text, description text, address_line1 text, neighbourhood text, postal_code text, latitude numeric(9,6), longitude numeric(9,6), website_url text, telephone text, categories text[] NOT NULL DEFAULT '{}', amenities text[] NOT NULL DEFAULT '{}', opening_hours jsonb, media jsonb NOT NULL DEFAULT '[]', source_url text, last_verified_at timestamptz, publish_status text NOT NULL DEFAULT 'DRAFT' CHECK (publish_status IN ('DRAFT','PUBLISHED','ARCHIVED')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(city_id,slug));
-- statement-breakpoint
ALTER TABLE profiles ADD COLUMN home_gym_id uuid REFERENCES gyms(id);
-- statement-breakpoint
CREATE TABLE gym_pricing (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), gym_id uuid NOT NULL REFERENCES gyms(id) ON DELETE CASCADE, plan_name text NOT NULL, recurring_cents integer NOT NULL CHECK (recurring_cents>=0), billing_frequency text NOT NULL CHECK (billing_frequency IN ('WEEKLY','BIWEEKLY','MONTHLY','QUARTERLY','ANNUALLY')), mandatory_recurring_fee_cents integer NOT NULL DEFAULT 0 CHECK (mandatory_recurring_fee_cents>=0), mandatory_annual_fee_cents integer NOT NULL DEFAULT 0 CHECK (mandatory_annual_fee_cents>=0), initiation_fee_cents integer NOT NULL DEFAULT 0 CHECK (initiation_fee_cents>=0), ongoing_monthly_cents integer, first_year_monthly_cents integer, pricing_complete boolean NOT NULL DEFAULT false, effective_from date, effective_to date, source_url text, last_verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE saved_gyms (profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, gym_id uuid NOT NULL REFERENCES gyms(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(profile_id,gym_id));
-- statement-breakpoint
CREATE TABLE clubs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), city_id uuid NOT NULL REFERENCES cities(id), slug text NOT NULL, name text NOT NULL, sport text NOT NULL, category text, description text, address text, website_url text, registration_url text, eligibility text, age_categories text[], season_information text, tags text[] NOT NULL DEFAULT '{}', source_url text, last_verified_at timestamptz, publish_status text NOT NULL DEFAULT 'DRAFT' CHECK (publish_status IN ('DRAFT','PUBLISHED','ARCHIVED')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(city_id,slug));
-- statement-breakpoint
CREATE TABLE disciplines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text NOT NULL UNIQUE, display_name text NOT NULL, metric_type text NOT NULL CHECK (metric_type IN ('TIME','REPETITIONS','WEIGHT','DISTANCE','POINTS','CUSTOM_NUMERIC')), unit text NOT NULL, ranking_direction text NOT NULL CHECK (ranking_direction IN ('LOWER_IS_BETTER','HIGHER_IS_BETTER')), evidence_type text NOT NULL, verification_checklist jsonb NOT NULL DEFAULT '[]', rules_version integer NOT NULL DEFAULT 1, official_eligible boolean NOT NULL DEFAULT true, community_eligible boolean NOT NULL DEFAULT true, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE divisions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text NOT NULL UNIQUE, display_label text NOT NULL, minimum_age integer, maximum_age integer, minimum_inclusive boolean NOT NULL DEFAULT true, maximum_inclusive boolean NOT NULL DEFAULT true, open boolean NOT NULL DEFAULT false, sex_category text CHECK (sex_category IN ('MEN','WOMEN','ALL')), active boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK (minimum_age IS NULL OR minimum_age>=0), CHECK (maximum_age IS NULL OR maximum_age>=minimum_age));
-- statement-breakpoint
CREATE TABLE events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), city_id uuid NOT NULL REFERENCES cities(id), slug text NOT NULL, name text NOT NULL, organizer text, category text, description text, start_at timestamptz NOT NULL, end_at timestamptz, registration_deadline timestamptz, registration_status text NOT NULL DEFAULT 'OPEN' CHECK (registration_status IN ('OPEN','CLOSED','NOT_APPLICABLE')), location text, external_registration_url text, entry_requirements text, image_url text, sport text, official_fitcalgary boolean NOT NULL DEFAULT false, tags text[] NOT NULL DEFAULT '{}', source_url text, event_status text NOT NULL DEFAULT 'ACTIVE' CHECK (event_status IN ('ACTIVE','CANCELLED','POSTPONED')), publish_status text NOT NULL DEFAULT 'DRAFT' CHECK (publish_status IN ('DRAFT','PUBLISHED','ARCHIVED')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(city_id,slug));
-- statement-breakpoint
CREATE TABLE leaderboards (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), region_id uuid NOT NULL REFERENCES regions(id), discipline_id uuid NOT NULL REFERENCES disciplines(id), division_id uuid NOT NULL REFERENCES divisions(id), event_id uuid REFERENCES events(id), board_type text NOT NULL CHECK (board_type IN ('OFFICIAL','COMMUNITY')), visible boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(region_id,discipline_id,division_id,event_id,board_type));
-- statement-breakpoint
CREATE TABLE submissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), profile_id uuid NOT NULL REFERENCES profiles(id), discipline_id uuid NOT NULL REFERENCES disciplines(id), parent_submission_id uuid REFERENCES submissions(id), claimed_metric numeric(20,6) NOT NULL, evidence_type text NOT NULL, checklist_acceptance jsonb NOT NULL DEFAULT '{}', status text NOT NULL CHECK (status IN ('DRAFT','UPLOADING','PENDING_REVIEW','APPROVED','REJECTED','CANCELLED')), assigned_judge_id uuid REFERENCES profiles(id), submitted_at timestamptz, decided_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE upload_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL REFERENCES submissions(id) ON DELETE CASCADE, storage_key text NOT NULL UNIQUE, provider_upload_id text, expected_size_bytes bigint NOT NULL CHECK (expected_size_bytes>0 AND expected_size_bytes<=4294967296), content_type text NOT NULL, checksum text, status text NOT NULL CHECK (status IN ('INITIALIZED','UPLOADING','COMPLETED','ABORTED','EXPIRED')), expires_at timestamptz NOT NULL, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE submission_evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL REFERENCES submissions(id) ON DELETE CASCADE, upload_session_id uuid NOT NULL REFERENCES upload_sessions(id), storage_key text NOT NULL UNIQUE, content_type text NOT NULL, size_bytes bigint NOT NULL, checksum text, retain_until timestamptz NOT NULL, evidence_deleted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE submission_reviews (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), submission_id uuid NOT NULL REFERENCES submissions(id), judge_profile_id uuid NOT NULL REFERENCES profiles(id), decision text NOT NULL CHECK (decision IN ('APPROVED','REJECTED','RESUBMISSION_REQUESTED')), checklist_responses jsonb NOT NULL, comments text, created_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), profile_id uuid NOT NULL REFERENCES profiles(id), submission_id uuid UNIQUE REFERENCES submissions(id), event_id uuid REFERENCES events(id), leaderboard_id uuid NOT NULL REFERENCES leaderboards(id), normalized_metric numeric(20,6) NOT NULL, display_metric text NOT NULL, verification_type text NOT NULL CHECK (verification_type IN ('IN_PERSON','COMMUNITY_REVIEWED')), verified_at timestamptz NOT NULL, verified_by uuid NOT NULL REFERENCES profiles(id), division_snapshot jsonb NOT NULL, profile_snapshot jsonb NOT NULL, discipline_rules_version integer NOT NULL, invalidated_at timestamptz, invalidation_reason text, created_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE ranking_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), leaderboard_id uuid NOT NULL REFERENCES leaderboards(id), result_id uuid NOT NULL REFERENCES results(id), previous_rank integer, current_rank integer NOT NULL CHECK (current_rank>0), calculated_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE notification_devices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, platform text NOT NULL CHECK (platform IN ('IOS','ANDROID','WEB')), token_hash text NOT NULL UNIQUE, encrypted_token text NOT NULL, enabled boolean NOT NULL DEFAULT true, last_seen_at timestamptz NOT NULL DEFAULT now(), invalidated_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, type text NOT NULL, title text NOT NULL, body text NOT NULL, deep_link text NOT NULL, dedupe_key text NOT NULL, delivery_status text NOT NULL DEFAULT 'QUEUED' CHECK (delivery_status IN ('QUEUED','SENDING','DELIVERED','FAILED','SUPPRESSED')), provider_message_id text, attempt_count integer NOT NULL DEFAULT 0, last_error_code text, sent_at timestamptz, opened_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(profile_id,dedupe_key));
-- statement-breakpoint
CREATE TABLE bans (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), profile_id uuid NOT NULL REFERENCES profiles(id), kind text NOT NULL CHECK (kind IN ('TEMPORARY_SUSPENSION','PERMANENT_BAN')), reason text NOT NULL, notes text, created_by uuid NOT NULL REFERENCES profiles(id), starts_at timestamptz NOT NULL DEFAULT now(), ends_at timestamptz, lifted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE moderation_actions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), target_profile_id uuid REFERENCES profiles(id), actor_profile_id uuid NOT NULL REFERENCES profiles(id), action text NOT NULL, reason text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE analytics_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), profile_id uuid REFERENCES profiles(id) ON DELETE SET NULL, anonymous_id_hash text, event_name text NOT NULL, properties jsonb NOT NULL DEFAULT '{}', occurred_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_profile_id uuid REFERENCES profiles(id), action text NOT NULL, entity_type text NOT NULL, entity_id text NOT NULL, before_data jsonb, after_data jsonb, metadata jsonb NOT NULL DEFAULT '{}', request_id text, created_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE app_settings (key text PRIMARY KEY, value jsonb NOT NULL, public boolean NOT NULL DEFAULT false, updated_by uuid REFERENCES profiles(id), updated_at timestamptz NOT NULL DEFAULT now());
-- statement-breakpoint
CREATE TABLE outbox_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_type text NOT NULL, dedupe_key text UNIQUE, payload jsonb NOT NULL, status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','PROCESSING','COMPLETE','FAILED')), available_at timestamptz NOT NULL DEFAULT now(), attempt_count integer NOT NULL DEFAULT 0, locked_at timestamptz, last_error text, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
-- statement-breakpoint
CREATE TABLE idempotency_keys (subject text NOT NULL, key text NOT NULL, request_hash text NOT NULL, response_status integer, response_body jsonb, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(subject,key));
-- statement-breakpoint
CREATE INDEX idx_gyms_public_city ON gyms(city_id,name) WHERE publish_status='PUBLISHED';
-- statement-breakpoint
CREATE INDEX idx_gym_pricing_gym ON gym_pricing(gym_id,ongoing_monthly_cents);
-- statement-breakpoint
CREATE INDEX idx_events_public_city_start ON events(city_id,start_at) WHERE publish_status='PUBLISHED';
-- statement-breakpoint
CREATE INDEX idx_submissions_queue ON submissions(status,assigned_judge_id,submitted_at) WHERE status='PENDING_REVIEW';
-- statement-breakpoint
CREATE INDEX idx_results_board_metric ON results(leaderboard_id,normalized_metric,verified_at) WHERE invalidated_at IS NULL;
-- statement-breakpoint
CREATE INDEX idx_evidence_retention ON submission_evidence(retain_until) WHERE evidence_deleted_at IS NULL;
-- statement-breakpoint
CREATE INDEX idx_notifications_delivery ON notifications(delivery_status,created_at) WHERE delivery_status IN ('QUEUED','FAILED');
-- statement-breakpoint
CREATE INDEX idx_outbox_available ON outbox_jobs(status,available_at) WHERE status IN ('PENDING','FAILED');
-- statement-breakpoint
CREATE INDEX idx_audit_entity ON audit_logs(entity_type,entity_id,created_at DESC);
-- statement-breakpoint
INSERT INTO provinces(code,name) VALUES('AB','Alberta');
-- statement-breakpoint
INSERT INTO regions(province_id,slug,name) SELECT id,'calgary-region','Calgary Region' FROM provinces WHERE code='AB';
-- statement-breakpoint
INSERT INTO cities(region_id,slug,name,latitude,longitude) SELECT id,'calgary','Calgary',51.0447,-114.0719 FROM regions WHERE slug='calgary-region';
-- statement-breakpoint
INSERT INTO disciplines(slug,display_name,metric_type,unit,ranking_direction,evidence_type,verification_checklist) VALUES ('bench-press','Bench Press','WEIGHT','kg','HIGHER_IS_BETTER','VIDEO','[{"key":"clear","label":"Video is sufficiently clear"},{"key":"visible","label":"Athlete and performance are visible"}]'),('5k-run','5K Run','TIME','seconds','LOWER_IS_BETTER','ACTIVITY_OR_OFFICIAL','[]'),('10k-run','10K Run','TIME','seconds','LOWER_IS_BETTER','ACTIVITY_OR_OFFICIAL','[]'),('push-ups','Push-Ups','REPETITIONS','reps','HIGHER_IS_BETTER','VIDEO','[{"key":"clear","label":"Video is sufficiently clear"},{"key":"visible","label":"Athlete and performance are visible"}]'),('pull-ups','Pull-Ups','REPETITIONS','reps','HIGHER_IS_BETTER','VIDEO','[{"key":"clear","label":"Video is sufficiently clear"},{"key":"visible","label":"Athlete and performance are visible"}]');
-- statement-breakpoint
INSERT INTO divisions(slug,display_label,minimum_age,maximum_age,minimum_inclusive,maximum_inclusive,open,sex_category) VALUES ('open-all','Open',NULL,NULL,true,true,true,'ALL'),('18-22-all','18–22',18,22,true,true,false,'ALL'),('23-29-all','23–29',23,29,true,true,false,'ALL'),('30-39-all','30–39',30,39,true,true,false,'ALL'),('40-plus-all','40+',40,NULL,true,true,false,'ALL');
-- statement-breakpoint
INSERT INTO app_settings(key,value,public) VALUES('brand','{"name":"FitCalgary Index","city":"Calgary","province":"Alberta"}',true),('feature_flags','{"PUBLIC_PROFILES":true,"COMMUNITY_LEADERBOARDS":true,"RESULT_SHARING":false,"QR_VERIFICATION":false,"GYM_LEADERBOARDS":false,"TRAINER_FEATURES":true,"DARK_MODE":false,"STRAVA_INTEGRATION":false,"FITALBERTA_PREVIEW":false}',true),('evidence_retention_days','14',false);
