import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { requireSubject } from '../auth/authorize.js';
import type { Db } from '../db/pool.js';

function profileId(request:FastifyRequest):string { requireSubject(request.principal);if(!request.profileId)throw new Error('Profile context is unavailable');return request.profileId; }
export async function registerAccountRoutes(app:FastifyInstance,db:Db,authenticate:(request:FastifyRequest)=>Promise<void>){
  app.get('/api/v1/auth/context',{preHandler:authenticate},async(request)=>({subject:request.principal!.subject,roles:request.principal!.roles,profileId:request.profileId??null,emailVerified:request.principal!.emailVerified}));
  app.get('/api/v1/profile',{preHandler:authenticate},async(request)=>{const result=await db.query(`SELECT p.id,p.username,p.display_name,p.photo_url,p.bio,p.date_of_birth,p.sex_category,p.home_gym_id,p.privacy,p.created_at,g.name AS home_gym_name FROM profiles p LEFT JOIN gyms g ON g.id=p.home_gym_id WHERE p.id=$1`,[profileId(request)]);return result.rows[0];});
  app.patch('/api/v1/profile',{preHandler:authenticate},async(request)=>{const body=z.object({username:z.string().regex(/^[a-z0-9_]{3,30}$/).optional(),displayName:z.string().trim().min(2).max(80).optional(),bio:z.string().trim().max(280).nullable().optional(),dateOfBirth:z.string().date().nullable().optional(),sexCategory:z.enum(['MEN','WOMEN','UNDISCLOSED']).nullable().optional(),homeGymId:z.string().uuid().nullable().optional(),privacy:z.object({publicProfile:z.boolean(),showGym:z.boolean()}).partial().optional()}).parse(request.body);const result=await db.query(`UPDATE profiles SET username=COALESCE($2,username),display_name=COALESCE($3,display_name),bio=CASE WHEN $4::boolean THEN $5 ELSE bio END,date_of_birth=CASE WHEN $6::boolean THEN $7::date ELSE date_of_birth END,sex_category=CASE WHEN $8::boolean THEN $9 ELSE sex_category END,home_gym_id=CASE WHEN $10::boolean THEN $11::uuid ELSE home_gym_id END,privacy=privacy||COALESCE($12::jsonb,'{}'),updated_at=now() WHERE id=$1 RETURNING id,username,display_name,bio,date_of_birth,sex_category,home_gym_id,privacy,updated_at`,[profileId(request),body.username??null,body.displayName??null,'bio'in body,body.bio??null,'dateOfBirth'in body,body.dateOfBirth??null,'sexCategory'in body,body.sexCategory??null,'homeGymId'in body,body.homeGymId??null,JSON.stringify(body.privacy??{})]);return result.rows[0];});
  app.get('/api/v1/saved-gyms',{preHandler:authenticate},async(request)=>{const result=await db.query(`SELECT g.id,g.slug,g.name,g.operator,g.neighbourhood,s.created_at FROM saved_gyms s JOIN gyms g ON g.id=s.gym_id WHERE s.profile_id=$1 ORDER BY s.created_at DESC`,[profileId(request)]);return{data:result.rows};});
  app.put('/api/v1/saved-gyms/:gymId',{preHandler:authenticate},async(request,reply)=>{const {gymId}=z.object({gymId:z.string().uuid()}).parse(request.params);await db.query('INSERT INTO saved_gyms(profile_id,gym_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[profileId(request),gymId]);return reply.code(204).send();});
  app.delete('/api/v1/saved-gyms/:gymId',{preHandler:authenticate},async(request,reply)=>{const {gymId}=z.object({gymId:z.string().uuid()}).parse(request.params);await db.query('DELETE FROM saved_gyms WHERE profile_id=$1 AND gym_id=$2',[profileId(request),gymId]);return reply.code(204).send();});
  app.get('/api/v1/notifications',{preHandler:authenticate},async(request)=>{const result=await db.query(`SELECT id,type,title,body,deep_link,created_at,opened_at FROM notifications WHERE profile_id=$1 ORDER BY created_at DESC LIMIT 100`,[profileId(request)]);return{data:result.rows};});
  app.get('/api/v1/watch/summary',{preHandler:authenticate},async(request)=>{const owner=profileId(request);const profile=await db.query('SELECT display_name,city_id FROM profiles WHERE id=$1',[owner]);const ranking=await db.query(`WITH ranked AS (SELECT rs.id,rs.profile_id,l.board_type,d.display_name AS discipline,v.display_label AS division,ROW_NUMBER() OVER(PARTITION BY l.id ORDER BY CASE WHEN d.ranking_direction='LOWER_IS_BETTER' THEN rs.normalized_metric END ASC NULLS LAST,CASE WHEN d.ranking_direction='HIGHER_IS_BETTER' THEN rs.normalized_metric END DESC NULLS LAST,rs.verified_at,rs.id)::int AS rank FROM results rs JOIN leaderboards l ON l.id=rs.leaderboard_id JOIN disciplines d ON d.id=l.discipline_id JOIN divisions v ON v.id=l.division_id WHERE rs.invalidated_at IS NULL) SELECT id,discipline,rank,division,board_type FROM ranked WHERE profile_id=$1 ORDER BY rank LIMIT 8`,[owner]);const results=await db.query(`SELECT rs.id,d.display_name AS discipline,rs.display_metric AS mark,rs.verified_at FROM results rs JOIN leaderboards l ON l.id=rs.leaderboard_id JOIN disciplines d ON d.id=l.discipline_id WHERE rs.profile_id=$1 AND rs.invalidated_at IS NULL ORDER BY rs.verified_at DESC LIMIT 8`,[owner]);const submissions=await db.query(`SELECT s.id,d.display_name AS discipline,s.status,s.updated_at FROM submissions s JOIN disciplines d ON d.id=s.discipline_id WHERE s.profile_id=$1 ORDER BY s.updated_at DESC LIMIT 8`,[owner]);const events=await db.query(`SELECT e.id,e.name,e.start_at,e.location FROM events e WHERE e.city_id=$1 AND e.publish_status='PUBLISHED' AND e.event_status='ACTIVE' AND e.start_at>=now() ORDER BY e.start_at LIMIT 8`,[profile.rows[0]?.city_id??null]);return{displayName:profile.rows[0]?.display_name??'Athlete',rankings:ranking.rows.map((row)=>({id:row.id,discipline:row.discipline,rank:Number(row.rank),division:row.division,boardType:row.board_type})),results:results.rows.map((row)=>({id:row.id,discipline:row.discipline,mark:row.mark,verifiedAt:row.verified_at})),submissions:submissions.rows.map((row)=>({id:row.id,discipline:row.discipline,status:row.status,updatedAt:row.updated_at})),events:events.rows.map((row)=>({id:row.id,name:row.name,startAt:row.start_at,location:row.location})),refreshedAt:new Date().toISOString()};});
}
