import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { Db } from '../db/pool.js';
import { requireRole } from '../auth/authorize.js';
import { normalizePrice } from '../domain/pricing/normalize.js';

const admin=(request:FastifyRequest)=>requireRole(request.principal,'ADMIN');
const gymInput=z.object({cityId:z.string().uuid(),brandId:z.string().uuid().nullable().optional(),slug:z.string().regex(/^[a-z0-9-]+$/).max(140),name:z.string().trim().min(2).max(180),operator:z.string().trim().max(180).nullable().optional(),description:z.string().trim().max(5000).nullable().optional(),addressLine1:z.string().trim().max(180).nullable().optional(),neighbourhood:z.string().trim().max(120).nullable().optional(),postalCode:z.string().trim().max(12).nullable().optional(),websiteUrl:z.string().url().nullable().optional(),telephone:z.string().trim().max(40).nullable().optional(),categories:z.array(z.string().max(80)).max(30).default([]),amenities:z.array(z.string().max(80)).max(100).default([]),sourceUrl:z.string().url().nullable().optional(),publishStatus:z.enum(['DRAFT','PUBLISHED','ARCHIVED']).default('DRAFT')});
const eventInput=z.object({cityId:z.string().uuid(),slug:z.string().regex(/^[a-z0-9-]+$/),name:z.string().trim().min(2).max(200),organizer:z.string().trim().max(180).nullable().optional(),category:z.string().trim().max(100).nullable().optional(),description:z.string().max(8000).nullable().optional(),startAt:z.string().datetime(),endAt:z.string().datetime().nullable().optional(),registrationDeadline:z.string().datetime().nullable().optional(),registrationStatus:z.enum(['OPEN','CLOSED','NOT_APPLICABLE']).default('OPEN'),location:z.string().max(240).nullable().optional(),externalRegistrationUrl:z.string().url().nullable().optional(),sport:z.string().max(100).nullable().optional(),officialFitcalgary:z.boolean().default(false),tags:z.array(z.string().max(80)).default([]),sourceUrl:z.string().url().nullable().optional(),eventStatus:z.enum(['ACTIVE','CANCELLED','POSTPONED']).default('ACTIVE'),publishStatus:z.enum(['DRAFT','PUBLISHED','ARCHIVED']).default('DRAFT')});

export async function registerAdminRoutes(app:FastifyInstance,db:Db,authenticate:(request:FastifyRequest)=>Promise<void>){
  app.get('/api/v1/admin/overview',{preHandler:authenticate},async(request)=>{admin(request);const result=await db.query(`SELECT (SELECT count(*) FROM profiles WHERE account_status='ACTIVE') AS total_users,(SELECT count(*) FROM submissions WHERE status='PENDING_REVIEW') AS pending_submissions,(SELECT count(*) FROM submission_evidence WHERE evidence_deleted_at IS NULL AND retain_until<now()+interval '48 hours') AS evidence_nearing_expiry,(SELECT count(*) FROM gyms WHERE publish_status='PUBLISHED') AS published_gyms,(SELECT count(*) FROM events WHERE publish_status='PUBLISHED' AND start_at>now()) AS upcoming_events,(SELECT count(*) FROM notifications WHERE delivery_status='FAILED') AS failed_notifications`);return result.rows[0];});
  app.get('/api/v1/admin/gyms',{preHandler:authenticate},async(request)=>{admin(request);const result=await db.query(`SELECT g.*,c.name AS city,(SELECT count(*) FROM gym_pricing p WHERE p.gym_id=g.id) AS pricing_count FROM gyms g JOIN cities c ON c.id=g.city_id ORDER BY g.updated_at DESC LIMIT 250`);return{data:result.rows};});
  app.post('/api/v1/admin/gyms',{preHandler:authenticate},async(request,reply)=>{admin(request);const b=gymInput.parse(request.body);const result=await db.query(`INSERT INTO gyms(city_id,brand_id,slug,name,operator,description,address_line1,neighbourhood,postal_code,website_url,telephone,categories,amenities,source_url,publish_status,last_verified_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,CASE WHEN $15='PUBLISHED' THEN now() END) RETURNING *`,[b.cityId,b.brandId??null,b.slug,b.name,b.operator??null,b.description??null,b.addressLine1??null,b.neighbourhood??null,b.postalCode??null,b.websiteUrl??null,b.telephone??null,b.categories,b.amenities,b.sourceUrl??null,b.publishStatus]);await audit(db,request,'GYM_CREATED','GYM',result.rows[0].id,null,result.rows[0]);return reply.code(201).send(result.rows[0]);});
  app.put('/api/v1/admin/gyms/:id',{preHandler:authenticate},async(request,reply)=>{admin(request);const {id}=z.object({id:z.string().uuid()}).parse(request.params);const b=gymInput.parse(request.body);const before=await db.query('SELECT * FROM gyms WHERE id=$1',[id]);if(!before.rows[0])return reply.code(404).send({error:{code:'NOT_FOUND',message:'Gym not found',requestId:request.id}});const result=await db.query(`UPDATE gyms SET city_id=$2,brand_id=$3,slug=$4,name=$5,operator=$6,description=$7,address_line1=$8,neighbourhood=$9,postal_code=$10,website_url=$11,telephone=$12,categories=$13,amenities=$14,source_url=$15,publish_status=$16,last_verified_at=CASE WHEN $16='PUBLISHED' THEN COALESCE(last_verified_at,now()) ELSE last_verified_at END,updated_at=now() WHERE id=$1 RETURNING *`,[id,b.cityId,b.brandId??null,b.slug,b.name,b.operator??null,b.description??null,b.addressLine1??null,b.neighbourhood??null,b.postalCode??null,b.websiteUrl??null,b.telephone??null,b.categories,b.amenities,b.sourceUrl??null,b.publishStatus]);await audit(db,request,'GYM_UPDATED','GYM',id,before.rows[0],result.rows[0]);return result.rows[0];});
  app.post('/api/v1/admin/gyms/:id/pricing',{preHandler:authenticate},async(request,reply)=>{admin(request);const {id}=z.object({id:z.string().uuid()}).parse(request.params);const b=z.object({planName:z.string().min(1).max(160),recurringCents:z.number().int().min(0),billingFrequency:z.enum(['WEEKLY','BIWEEKLY','MONTHLY','QUARTERLY','ANNUALLY']),mandatoryRecurringFeeCents:z.number().int().min(0).default(0),mandatoryAnnualFeeCents:z.number().int().min(0).default(0),initiationFeeCents:z.number().int().min(0).default(0),pricingComplete:z.boolean(),sourceUrl:z.string().url().nullable().optional(),effectiveFrom:z.string().date().nullable().optional()}).parse(request.body);const normalized=normalizePrice({recurringCents:b.recurringCents,frequency:b.billingFrequency,mandatoryRecurringFeeCents:b.mandatoryRecurringFeeCents,mandatoryAnnualFeeCents:b.mandatoryAnnualFeeCents,initiationFeeCents:b.initiationFeeCents,complete:b.pricingComplete});const result=await db.query(`INSERT INTO gym_pricing(gym_id,plan_name,recurring_cents,billing_frequency,mandatory_recurring_fee_cents,mandatory_annual_fee_cents,initiation_fee_cents,ongoing_monthly_cents,first_year_monthly_cents,pricing_complete,source_url,effective_from,last_verified_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,now()) RETURNING *`,[id,b.planName,b.recurringCents,b.billingFrequency,b.mandatoryRecurringFeeCents,b.mandatoryAnnualFeeCents,b.initiationFeeCents,normalized.ongoingMonthlyCents,normalized.firstYearMonthlyCents,b.pricingComplete,b.sourceUrl??null,b.effectiveFrom??null]);await audit(db,request,'GYM_PRICING_CREATED','GYM',id,null,result.rows[0]);return reply.code(201).send(result.rows[0]);});
  app.get('/api/v1/admin/events',{preHandler:authenticate},async(request)=>{admin(request);const result=await db.query('SELECT e.*,c.name AS city FROM events e JOIN cities c ON c.id=e.city_id ORDER BY e.start_at DESC LIMIT 250');return{data:result.rows};});
  app.post('/api/v1/admin/events',{preHandler:authenticate},async(request,reply)=>{admin(request);const b=eventInput.parse(request.body);const result=await db.query(`INSERT INTO events(city_id,slug,name,organizer,category,description,start_at,end_at,registration_deadline,registration_status,location,external_registration_url,sport,official_fitcalgary,tags,source_url,event_status,publish_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) RETURNING *`,[b.cityId,b.slug,b.name,b.organizer??null,b.category??null,b.description??null,b.startAt,b.endAt??null,b.registrationDeadline??null,b.registrationStatus,b.location??null,b.externalRegistrationUrl??null,b.sport??null,b.officialFitcalgary,b.tags,b.sourceUrl??null,b.eventStatus,b.publishStatus]);await audit(db,request,'EVENT_CREATED','EVENT',result.rows[0].id,null,result.rows[0]);return reply.code(201).send(result.rows[0]);});
  app.put('/api/v1/admin/settings/:key',{preHandler:authenticate},async(request)=>{admin(request);const {key}=z.object({key:z.string().regex(/^[a-z0-9_]+$/)}).parse(request.params);const body=z.object({value:z.unknown(),public:z.boolean().default(false)}).parse(request.body);const before=await db.query('SELECT * FROM app_settings WHERE key=$1',[key]);const result=await db.query(`INSERT INTO app_settings(key,value,public,updated_by) VALUES($1,$2,$3,$4) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,public=EXCLUDED.public,updated_by=EXCLUDED.updated_by,updated_at=now() RETURNING *`,[key,JSON.stringify(body.value),body.public,request.profileId]);await audit(db,request,'SETTING_UPDATED','SETTING',key,before.rows[0]??null,result.rows[0]);return result.rows[0];});
  app.put('/api/v1/admin/users/:profileId/roles/:role',{preHandler:authenticate},async(request,reply)=>{admin(request);const p=z.object({profileId:z.string().uuid(),role:z.enum(['USER','MODERATOR','ADMIN','PERSONAL_TRAINER','JUDGE'])}).parse(request.params);await db.query(`INSERT INTO user_roles(profile_id,role,granted_by) VALUES($1,$2,$3) ON CONFLICT DO NOTHING`,[p.profileId,p.role,request.profileId]);await audit(db,request,'ROLE_GRANTED','PROFILE',p.profileId,null,{role:p.role});return reply.code(204).send();});
  app.delete('/api/v1/admin/users/:profileId/roles/:role',{preHandler:authenticate},async(request,reply)=>{admin(request);const p=z.object({profileId:z.string().uuid(),role:z.enum(['USER','MODERATOR','ADMIN','PERSONAL_TRAINER','JUDGE'])}).parse(request.params);if(p.profileId===request.profileId&&p.role==='ADMIN')return reply.code(409).send({error:{code:'SELF_ADMIN_REMOVAL',message:'An administrator cannot remove their own admin role',requestId:request.id}});await db.query('DELETE FROM user_roles WHERE profile_id=$1 AND role=$2',[p.profileId,p.role]);await audit(db,request,'ROLE_REVOKED','PROFILE',p.profileId,{role:p.role},null);return reply.code(204).send();});
  app.get('/api/v1/admin/audit-log',{preHandler:authenticate},async(request)=>{admin(request);const result=await db.query('SELECT a.*,p.display_name AS actor FROM audit_logs a LEFT JOIN profiles p ON p.id=a.actor_profile_id ORDER BY a.created_at DESC LIMIT 500');return{data:result.rows};});
}
async function audit(db:Db,request:FastifyRequest,action:string,entityType:string,entityId:string,before:unknown,after:unknown){await db.query(`INSERT INTO audit_logs(actor_profile_id,action,entity_type,entity_id,before_data,after_data,request_id) VALUES($1,$2,$3,$4,$5,$6,$7)`,[request.profileId,action,entityType,entityId,before===null?null:JSON.stringify(before),after===null?null:JSON.stringify(after),request.id]);}
