import type { FastifyInstance, FastifyRequest } from 'fastify';
import type pg from 'pg';
import { z } from 'zod';
import type { Db } from '../db/pool.js';
import { requireRole } from '../auth/authorize.js';
import { EvidenceStore } from '../storage/evidence.js';
import type { Env } from '../config/env.js';

async function ranks(client:pg.PoolClient,leaderboardId:string,direction:string){const order=direction==='LOWER_IS_BETTER'?'ASC':'DESC';const result=await client.query(`SELECT rs.id,rs.profile_id,ROW_NUMBER() OVER(ORDER BY rs.normalized_metric ${order},rs.verified_at,rs.id)::int AS rank FROM results rs WHERE rs.leaderboard_id=$1 AND rs.invalidated_at IS NULL ORDER BY rank`,[leaderboardId]);return result.rows as {id:string;profile_id:string;rank:number}[];}

export async function registerJudgeRoutes(app:FastifyInstance,db:Db,env:Env,authenticate:(request:FastifyRequest)=>Promise<void>){const store=new EvidenceStore(env);
  app.get('/api/v1/judge/queue',{preHandler:authenticate},async(request)=>{requireRole(request.principal,'JUDGE','ADMIN');const result=await db.query(`SELECT s.id,s.claimed_metric,s.evidence_type,s.submitted_at,s.assigned_judge_id,d.display_name AS discipline,p.display_name AS athlete,e.retain_until,e.evidence_deleted_at,(s.parent_submission_id IS NOT NULL) AS resubmission FROM submissions s JOIN disciplines d ON d.id=s.discipline_id JOIN profiles p ON p.id=s.profile_id LEFT JOIN submission_evidence e ON e.submission_id=s.id WHERE s.status='PENDING_REVIEW' AND (s.assigned_judge_id IS NULL OR s.assigned_judge_id=$1 OR $2::boolean) ORDER BY e.retain_until NULLS LAST,s.submitted_at LIMIT 100`,[request.profileId,request.principal!.roles.includes('ADMIN')]);return{data:result.rows};});
  app.get('/api/v1/judge/submissions/:id/evidence',{preHandler:authenticate},async(request,reply)=>{requireRole(request.principal,'JUDGE','ADMIN');const {id}=z.object({id:z.string().uuid()}).parse(request.params);const row=await db.query(`SELECT e.storage_key,e.evidence_deleted_at,s.assigned_judge_id FROM submission_evidence e JOIN submissions s ON s.id=e.submission_id WHERE s.id=$1`,[id]);if(!row.rows[0])return reply.code(404).send({error:{code:'NOT_FOUND',message:'Evidence not found',requestId:request.id}});if(row.rows[0].assigned_judge_id&&row.rows[0].assigned_judge_id!==request.profileId&&!request.principal!.roles.includes('ADMIN'))return reply.code(403).send({error:{code:'NOT_ASSIGNED',message:'Submission is assigned to another judge',requestId:request.id}});if(row.rows[0].evidence_deleted_at)return reply.code(410).send({error:{code:'EVIDENCE_DELETED',message:'Evidence was deleted under the retention policy',requestId:request.id}});await db.query(`INSERT INTO audit_logs(actor_profile_id,action,entity_type,entity_id,request_id) VALUES($1,'EVIDENCE_VIEWED','SUBMISSION',$2,$3)`,[request.profileId,id,request.id]);return{url:await store.playbackUrl(row.rows[0].storage_key),expiresIn:env.SIGNED_URL_TTL_SECONDS};});
  app.post('/api/v1/judge/submissions/:id/decision',{preHandler:authenticate},async(request,reply)=>{requireRole(request.principal,'JUDGE','ADMIN');const {id}=z.object({id:z.string().uuid()}).parse(request.params);const body=z.object({decision:z.enum(['APPROVED','REJECTED','RESUBMISSION_REQUESTED']),checklistResponses:z.record(z.string(),z.boolean()),comments:z.string().trim().max(2000).optional()}).parse(request.body);if(body.decision!=='APPROVED'&&!body.comments)return reply.code(422).send({error:{code:'COMMENT_REQUIRED',message:'A clear judge comment is required when a result is not approved',requestId:request.id}});const client=await db.connect();try{await client.query('BEGIN');const locked=await client.query(`SELECT s.*,d.ranking_direction,d.rules_version,d.display_name,p.date_of_birth,p.sex_category,p.home_gym_id,p.display_name FROM submissions s JOIN disciplines d ON d.id=s.discipline_id JOIN profiles p ON p.id=s.profile_id WHERE s.id=$1 FOR UPDATE OF s`,[id]);const submission=locked.rows[0];if(!submission){await client.query('ROLLBACK');return reply.code(404).send({error:{code:'NOT_FOUND',message:'Submission not found',requestId:request.id}});}if(submission.status!=='PENDING_REVIEW'){await client.query('ROLLBACK');return reply.code(409).send({error:{code:'ALREADY_DECIDED',message:'Submission is no longer pending review',requestId:request.id}});}if(submission.profile_id===request.profileId){await client.query('ROLLBACK');return reply.code(403).send({error:{code:'SELF_REVIEW_FORBIDDEN',message:'A judge cannot review their own result',requestId:request.id}});}if(submission.assigned_judge_id&&submission.assigned_judge_id!==request.profileId&&!request.principal!.roles.includes('ADMIN')){await client.query('ROLLBACK');return reply.code(403).send({error:{code:'NOT_ASSIGNED',message:'Submission is assigned to another judge',requestId:request.id}});}await client.query(`INSERT INTO submission_reviews(submission_id,judge_profile_id,decision,checklist_responses,comments) VALUES($1,$2,$3,$4,$5)`,[id,request.profileId,body.decision,JSON.stringify(body.checklistResponses),body.comments??null]);const finalStatus=body.decision==='APPROVED'?'APPROVED':'REJECTED';await client.query(`UPDATE submissions SET status=$2,assigned_judge_id=COALESCE(assigned_judge_id,$3),decided_at=now(),updated_at=now() WHERE id=$1`,[id,finalStatus,request.profileId]);
      if(body.decision==='APPROVED'){const context=await client.query(`SELECT r.id AS region_id,v.id AS division_id,v.display_label FROM cities c JOIN regions r ON r.id=c.region_id CROSS JOIN divisions v WHERE c.id=(SELECT city_id FROM profiles WHERE id=$1) AND v.slug='open-all'`,[submission.profile_id]);if(!context.rows[0])throw new Error('Profile region or Open division is not configured');const {region_id,division_id,display_label}=context.rows[0];const lockKey=`${region_id}:${submission.discipline_id}:${division_id}:COMMUNITY`;await client.query('SELECT pg_advisory_xact_lock(hashtext($1))',[lockKey]);let board=await client.query(`SELECT id FROM leaderboards WHERE region_id=$1 AND discipline_id=$2 AND division_id=$3 AND event_id IS NULL AND board_type='COMMUNITY' LIMIT 1`,[region_id,submission.discipline_id,division_id]);if(!board.rows[0])board=await client.query(`INSERT INTO leaderboards(region_id,discipline_id,division_id,board_type) VALUES($1,$2,$3,'COMMUNITY') RETURNING id`,[region_id,submission.discipline_id,division_id]);const boardId=board.rows[0].id;const before=await ranks(client,boardId,submission.ranking_direction);const displayMetric=submission.ranking_direction==='LOWER_IS_BETTER'?formatTime(Number(submission.claimed_metric)):`${Number(submission.claimed_metric)} ${submission.ranking_direction==='HIGHER_IS_BETTER'?'reps':''}`.trim();const inserted=await client.query(`INSERT INTO results(profile_id,submission_id,leaderboard_id,normalized_metric,display_metric,verification_type,verified_at,verified_by,division_snapshot,profile_snapshot,discipline_rules_version) VALUES($1,$2,$3,$4,$5,'COMMUNITY_REVIEWED',now(),$6,$7,$8,$9) RETURNING id`,[submission.profile_id,id,boardId,submission.claimed_metric,displayMetric,request.profileId,JSON.stringify({id:division_id,label:display_label}),JSON.stringify({displayName:submission.display_name,sexCategory:submission.sex_category,homeGymId:submission.home_gym_id}),submission.rules_version]);const after=await ranks(client,boardId,submission.ranking_direction);for(const current of after){const previous=before.find((item)=>item.id===current.id)?.rank??null;await client.query(`INSERT INTO ranking_history(leaderboard_id,result_id,previous_rank,current_rank) VALUES($1,$2,$3,$4)`,[boardId,current.id,previous,current.rank]);if(previous!==null&&current.rank>previous){await client.query(`INSERT INTO outbox_jobs(job_type,dedupe_key,payload) VALUES('NOTIFICATION',$1,$2) ON CONFLICT(dedupe_key) DO NOTHING`,[`passed:${inserted.rows[0].id}:${current.id}`,JSON.stringify({type:'LEADERBOARD_PASSED',leaderboardId:boardId,newRank:current.rank,profileId:current.profile_id,passingAthleteDisplayName:submission.display_name})]);}}}
      await client.query(`INSERT INTO outbox_jobs(job_type,dedupe_key,payload) VALUES('NOTIFICATION',$1,$2) ON CONFLICT(dedupe_key) DO NOTHING`,[`${finalStatus.toLowerCase()}:${id}`,JSON.stringify({type:`SUBMISSION_${finalStatus}`,submissionId:id,profileId:submission.profile_id})]);await client.query(`INSERT INTO audit_logs(actor_profile_id,action,entity_type,entity_id,after_data,request_id) VALUES($1,$2,'SUBMISSION',$3,$4,$5)`,[request.profileId,`RESULT_${finalStatus}`,id,JSON.stringify({decision:body.decision,checklistResponses:body.checklistResponses}),request.id]);await client.query('COMMIT');return{status:finalStatus};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}});
}
function formatTime(seconds:number):string{const minutes=Math.floor(seconds/60);const remainder=Math.round(seconds%60);return`${minutes}:${String(remainder).padStart(2,'0')}`;}
