import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import type { Db } from '../db/pool.js';

const listQuery=z.object({q:z.string().trim().max(120).optional(),city:z.string().trim().max(80).default('calgary'),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20),category:z.string().trim().max(80).optional()});
export async function registerPublicRoutes(app:FastifyInstance,db:Db){
  app.get('/api/v1/gyms',async(request)=>{const q=listQuery.parse(request.query);const offset=(q.page-1)*q.pageSize;const search=q.q?`%${q.q}%`:null;const category=q.category??null;const result=await db.query(`SELECT g.id,g.slug,g.name,g.operator,g.neighbourhood AS area,c.name AS city,g.categories,MIN(p.ongoing_monthly_cents) FILTER (WHERE p.pricing_complete) AS lowest_ongoing_monthly_cents,COALESCE(bool_and(p.pricing_complete),false) AS pricing_complete,g.updated_at,COUNT(*) OVER() AS total FROM gyms g JOIN cities c ON c.id=g.city_id LEFT JOIN gym_pricing p ON p.gym_id=g.id WHERE g.publish_status='PUBLISHED' AND c.slug=$1 AND ($2::text IS NULL OR g.name ILIKE $2 OR COALESCE(g.operator,'') ILIKE $2 OR COALESCE(g.neighbourhood,'') ILIKE $2) AND ($3::text IS NULL OR $3=ANY(g.categories)) GROUP BY g.id,c.name ORDER BY g.name LIMIT $4 OFFSET $5`,[q.city,search,category,q.pageSize,offset]);return{data:result.rows.map((row)=>({...row,lowest_ongoing_monthly_cents:row.lowest_ongoing_monthly_cents===null?null:Number(row.lowest_ongoing_monthly_cents),total:undefined})),page:q.page,pageSize:q.pageSize,total:Number(result.rows[0]?.total??0)};});
  app.get('/api/v1/gyms/:slug',async(request,reply)=>{const {slug}=z.object({slug:z.string().max(180)}).parse(request.params);const result=await db.query(`SELECT g.*,c.name AS city,c.slug AS city_slug,COALESCE(json_agg(p ORDER BY p.ongoing_monthly_cents) FILTER (WHERE p.id IS NOT NULL),'[]') AS pricing FROM gyms g JOIN cities c ON c.id=g.city_id LEFT JOIN gym_pricing p ON p.gym_id=g.id WHERE g.slug=$1 AND g.publish_status='PUBLISHED' GROUP BY g.id,c.name,c.slug`,[slug]);if(!result.rows[0])return reply.code(404).send({error:{code:'NOT_FOUND',message:'Gym not found',requestId:request.id}});return result.rows[0];});
  app.get('/api/v1/clubs',async(request)=>{const q=listQuery.parse(request.query);const search=q.q?`%${q.q}%`:null;const result=await db.query(`SELECT cl.id,cl.slug,cl.name,cl.sport,cl.category,cl.description,cl.registration_url,cl.tags,c.name AS city,COUNT(*) OVER() AS total FROM clubs cl JOIN cities c ON c.id=cl.city_id WHERE cl.publish_status='PUBLISHED' AND c.slug=$1 AND ($2::text IS NULL OR cl.name ILIKE $2 OR cl.sport ILIKE $2) ORDER BY cl.name LIMIT $3 OFFSET $4`,[q.city,search,q.pageSize,(q.page-1)*q.pageSize]);return{data:result.rows.map((row)=>({...row,total:undefined})),page:q.page,pageSize:q.pageSize,total:Number(result.rows[0]?.total??0)};});
  app.get('/api/v1/events',async(request)=>{const q=listQuery.extend({month:z.string().regex(/^\d{4}-\d{2}$/).optional(),open:z.coerce.boolean().optional()}).parse(request.query);const search=q.q?`%${q.q}%`:null;const result=await db.query(`SELECT e.id,e.slug,e.name,e.organizer,e.category,e.start_at,e.end_at,e.registration_status,e.location,e.external_registration_url,e.sport,e.event_status,c.name AS city,COUNT(*) OVER() AS total FROM events e JOIN cities c ON c.id=e.city_id WHERE e.publish_status='PUBLISHED' AND c.slug=$1 AND ($2::text IS NULL OR e.name ILIKE $2 OR COALESCE(e.sport,'') ILIKE $2) AND ($3::text IS NULL OR to_char(e.start_at,'YYYY-MM')=$3) AND ($4::boolean IS NULL OR $4=false OR e.registration_status='OPEN') ORDER BY e.start_at LIMIT $5 OFFSET $6`,[q.city,search,q.month??null,q.open??null,q.pageSize,(q.page-1)*q.pageSize]);return{data:result.rows.map((row)=>({...row,total:undefined})),page:q.page,pageSize:q.pageSize,total:Number(result.rows[0]?.total??0)};});
  app.get('/api/v1/disciplines',async()=>{const result=await db.query('SELECT id,slug,display_name,metric_type,unit,ranking_direction,evidence_type,official_eligible,community_eligible,rules_version FROM disciplines WHERE active=true ORDER BY display_name');return{data:result.rows};});
  app.get('/api/v1/leaderboards/:id',async(request,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params);const board=await db.query(`SELECT l.id,l.board_type,d.id AS discipline_id,d.slug,d.display_name,d.metric_type,d.unit,d.ranking_direction,v.id AS division_id,v.display_label,r.id AS region_id,r.name AS region_name FROM leaderboards l JOIN disciplines d ON d.id=l.discipline_id JOIN divisions v ON v.id=l.division_id JOIN regions r ON r.id=l.region_id WHERE l.id=$1 AND l.visible=true`,[id]);if(!board.rows[0])return reply.code(404).send({error:{code:'NOT_FOUND',message:'Leaderboard not found',requestId:request.id}});const direction=board.rows[0].ranking_direction==='LOWER_IS_BETTER'?'ASC':'DESC';const entries=await db.query(`SELECT rs.id AS result_id,ROW_NUMBER() OVER(ORDER BY rs.normalized_metric ${direction},rs.verified_at,rs.id) AS rank,(SELECT rh.previous_rank FROM ranking_history rh WHERE rh.result_id=rs.id ORDER BY rh.calculated_at DESC LIMIT 1) AS previous_rank,p.display_name,g.name AS gym_name,rs.normalized_metric,rs.display_metric,rs.verified_at,rs.verification_type FROM results rs JOIN profiles p ON p.id=rs.profile_id LEFT JOIN gyms g ON g.id=p.home_gym_id WHERE rs.leaderboard_id=$1 AND rs.invalidated_at IS NULL AND COALESCE((p.privacy->>'publicProfile')::boolean,true)=true ORDER BY rank LIMIT 100`,[id]);const meta=board.rows[0];return{id:meta.id,boardType:meta.board_type,discipline:{id:meta.discipline_id,slug:meta.slug,name:meta.display_name,metricType:meta.metric_type,unit:meta.unit,rankingDirection:meta.ranking_direction},division:{id:meta.division_id,label:meta.display_label},region:{id:meta.region_id,name:meta.region_name},entries:entries.rows.map((row)=>({...row,rank:Number(row.rank),previous_rank:row.previous_rank===null?null:Number(row.previous_rank)}))};});
}
