import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { Db } from '../db/pool.js';
import type { Env } from '../config/env.js';
import { requireSubject } from '../auth/authorize.js';
import { EvidenceStore } from '../storage/evidence.js';

function profileId(request:FastifyRequest):string { requireSubject(request.principal);if(!request.profileId)throw new Error('Profile context missing');return request.profileId; }
export async function registerSubmissionRoutes(app:FastifyInstance,db:Db,env:Env,authenticate:(request:FastifyRequest)=>Promise<void>){const store=new EvidenceStore(env);
  app.get('/api/v1/submissions',{preHandler:authenticate},async(request)=>{const result=await db.query(`SELECT s.id,s.claimed_metric,s.evidence_type,s.status,s.submitted_at,s.decided_at,s.created_at,d.display_name AS discipline,(SELECT json_agg(json_build_object('decision',r.decision,'comments',r.comments,'checklist',r.checklist_responses,'createdAt',r.created_at) ORDER BY r.created_at) FROM submission_reviews r WHERE r.submission_id=s.id) AS reviews FROM submissions s JOIN disciplines d ON d.id=s.discipline_id WHERE s.profile_id=$1 ORDER BY s.created_at DESC`,[profileId(request)]);return{data:result.rows};});
  app.post('/api/v1/submissions',{preHandler:authenticate},async(request,reply)=>{const body=z.object({disciplineId:z.string().uuid(),claimedMetric:z.coerce.number().positive(),evidenceType:z.enum(['VIDEO','ACTIVITY_FILE','EXTERNAL_ACTIVITY_REFERENCE']),checklistAcceptance:z.record(z.string(),z.boolean()),parentSubmissionId:z.string().uuid().optional()}).parse(request.body);const owner=profileId(request);const blocked=await db.query(`SELECT 1 FROM bans WHERE profile_id=$1 AND lifted_at IS NULL AND (ends_at IS NULL OR ends_at>now()) LIMIT 1`,[owner]);if(blocked.rowCount)return reply.code(403).send({error:{code:'ACCOUNT_RESTRICTED',message:'This account cannot submit results',requestId:request.id}});const discipline=await db.query('SELECT id,evidence_type,verification_checklist FROM disciplines WHERE id=$1 AND active=true AND community_eligible=true',[body.disciplineId]);if(!discipline.rows[0])return reply.code(422).send({error:{code:'DISCIPLINE_INELIGIBLE',message:'This discipline is unavailable for community submissions',requestId:request.id}});const result=await db.query(`INSERT INTO submissions(profile_id,discipline_id,parent_submission_id,claimed_metric,evidence_type,checklist_acceptance,status) VALUES($1,$2,$3,$4,$5,$6,'DRAFT') RETURNING id,status,created_at`,[owner,body.disciplineId,body.parentSubmissionId??null,body.claimedMetric,body.evidenceType,JSON.stringify(body.checklistAcceptance)]);return reply.code(201).send(result.rows[0]);});
  app.post('/api/v1/submissions/:id/uploads',{preHandler:authenticate},async(request,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params);const body=z.object({contentType:z.string().max(120),sizeBytes:z.number().int().positive()}).parse(request.body);const owner=profileId(request);const submission=await db.query(`SELECT id,status FROM submissions WHERE id=$1 AND profile_id=$2`,[id,owner]);if(!submission.rows[0])return reply.code(404).send({error:{code:'NOT_FOUND',message:'Submission not found',requestId:request.id}});if(!['DRAFT','UPLOADING'].includes(submission.rows[0].status))return reply.code(409).send({error:{code:'INVALID_STATE',message:'Submission cannot accept a new upload',requestId:request.id}});const upload=await store.begin(request.principal!.subject,id,body.contentType,body.sizeBytes);const record=await db.query(`INSERT INTO upload_sessions(submission_id,storage_key,provider_upload_id,expected_size_bytes,content_type,status,expires_at) VALUES($1,$2,$3,$4,$5,'INITIALIZED',now()+interval '24 hours') RETURNING id,expires_at`,[id,upload.key,upload.uploadId,body.sizeBytes,body.contentType]);await db.query(`UPDATE submissions SET status='UPLOADING',updated_at=now() WHERE id=$1`,[id]);return reply.code(201).send({id:record.rows[0].id,partSizeBytes:16*1024*1024,expiresAt:record.rows[0].expires_at});});
  app.post('/api/v1/uploads/:id/parts/:partNumber',{preHandler:authenticate},async(request,reply)=>{const params=z.object({id:z.string().uuid(),partNumber:z.coerce.number().int().min(1).max(10_000)}).parse(request.params);const row=await db.query(`SELECT u.storage_key,u.provider_upload_id,u.expires_at FROM upload_sessions u JOIN submissions s ON s.id=u.submission_id WHERE u.id=$1 AND s.profile_id=$2 AND u.status IN ('INITIALIZED','UPLOADING')`,[params.id,profileId(request)]);if(!row.rows[0])return reply.code(404).send({error:{code:'NOT_FOUND',message:'Upload session not found',requestId:request.id}});if(new Date(row.rows[0].expires_at)<new Date())return reply.code(410).send({error:{code:'UPLOAD_EXPIRED',message:'Upload session expired',requestId:request.id}});await db.query(`UPDATE upload_sessions SET status='UPLOADING',updated_at=now() WHERE id=$1`,[params.id]);return{url:await store.signPart(row.rows[0].storage_key,row.rows[0].provider_upload_id,params.partNumber),expiresIn:env.SIGNED_URL_TTL_SECONDS};});
  app.post('/api/v1/uploads/:id/finalize',{preHandler:authenticate},async(request,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params);const body=z.object({parts:z.array(z.object({ETag:z.string().min(1),PartNumber:z.number().int().min(1).max(10_000)})).min(1).max(10_000),checksum:z.string().max(256).optional()}).parse(request.body);const owner=profileId(request);const row=await db.query(`SELECT u.*,s.status AS submission_status FROM upload_sessions u JOIN submissions s ON s.id=u.submission_id WHERE u.id=$1 AND s.profile_id=$2`,[id,owner]);const upload=row.rows[0];if(!upload)return reply.code(404).send({error:{code:'NOT_FOUND',message:'Upload session not found',requestId:request.id}});if(upload.status==='COMPLETED'){const existing=await db.query('SELECT id,retain_until FROM submission_evidence WHERE upload_session_id=$1',[id]);return{evidenceId:existing.rows[0]?.id,retainUntil:existing.rows[0]?.retain_until,status:'PENDING_REVIEW'};}if(!['INITIALIZED','UPLOADING'].includes(upload.status))return reply.code(409).send({error:{code:'INVALID_STATE',message:'Upload cannot be finalized',requestId:request.id}});const head=await store.complete(upload.storage_key,upload.provider_upload_id,body.parts);if(Number(head.ContentLength)!==Number(upload.expected_size_bytes))return reply.code(422).send({error:{code:'SIZE_MISMATCH',message:'Uploaded evidence size did not match the declared size',requestId:request.id}});const client=await db.connect();try{await client.query('BEGIN');const evidence=await client.query(`INSERT INTO submission_evidence(submission_id,upload_session_id,storage_key,content_type,size_bytes,checksum,retain_until) VALUES($1,$2,$3,$4,$5,$6,now()+($7||' days')::interval) RETURNING id,retain_until`,[upload.submission_id,id,upload.storage_key,upload.content_type,upload.expected_size_bytes,body.checksum??null,env.EVIDENCE_RETENTION_DAYS]);await client.query(`UPDATE upload_sessions SET status='COMPLETED',completed_at=now(),updated_at=now() WHERE id=$1`,[id]);await client.query(`UPDATE submissions SET status='PENDING_REVIEW',submitted_at=COALESCE(submitted_at,now()),updated_at=now() WHERE id=$1`,[upload.submission_id]);await client.query(`INSERT INTO outbox_jobs(job_type,dedupe_key,payload) VALUES('NOTIFICATION',$1,$2) ON CONFLICT(dedupe_key) DO NOTHING`,[`submission-received:${upload.submission_id}`,JSON.stringify({type:'SUBMISSION_RECEIVED',submissionId:upload.submission_id,profileId:owner})]);await client.query('COMMIT');return{evidenceId:evidence.rows[0].id,retainUntil:evidence.rows[0].retain_until,status:'PENDING_REVIEW'};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}});
}
